### PR TITLE
Implement authentication

### PR DESCRIPTION
**Pull request by mridubhatnagar**
Handles issue https://github.com/hseritt/repositext/issues/3

Home Page
repositext_home

Login Page
repositext_login

SignUp Page
repositext_signup

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
- [ ] home page needs to be changed from /docweb/ to /user/home/.

- [ ] Resolving point 1. It would also help in redirecting the user to the home page. Instead of the main app on clicking Repositext on the left-hand corner of the above-shown screenshots.

- [ ] On successful login. The user has to be redirected to /docweb/ url. And a logout option needs to be added in the top right corner of the navbar in the existing template.

- [ ] On successful logout. User should be back to /user/home/ page. A message can be shown. Saying you have logged out.

**Comment by hseritt** [comment]
Hi! Thanks for this :-) !!! 

Do you have more work to do with it yourself? or have you gone as far as you feel you can?

Thanks again!

**Comment by mridubhatnagar** [comment]
> Hi! Thanks for this :-) !!!
> 
> Do you have more work to do with it yourself? or have you gone as far as you feel you can?
> 
> Thanks again!

You're welcome.
The unchecked boxes need to be struck off. Only then it would be complete. I'll fix these.

**Comment by hseritt** [comment]
No worries. Take your time and thanks again for the help!

**Comment by mridubhatnagar** [comment]
Continued Workflow.

Once the user successfully logs in. He/She gets redirected to the docweb homepage. And, an option to logout is shown at the topmost right corner of the navbar.

docweb

**Comment by mridubhatnagar** [comment]
Hey, so I have completed it. Now, what remains is the beautification part. So, that complete project UI is in sync. 

I only know a bit of HTML and bootstrap on the basis of that I coded the current templates. However, I am interested in getting a hang of CSS too. I think https://github.com/hseritt/repositext/issues/11 issue might help me in doing so. 

We the changes seem to be fine. This can be merged. And I can try on making the UI look good with the PR for issue 11.

**Comment by hseritt** [comment]
Looks good! I will have a look at your branch and test it out. Thanks again :-)

**Comment by hseritt** [comment]
Hi Mridu,

I've sent you a private note about this pull request.

-Harlin

**Comment by mridubhatnagar** [comment]
Tasks 

- [ ] Scrape off the apps.user. Merge user app changes into apps.docweb.

- [ ] Remove registration page.

- [ ] Instead of /user/home/ make it to /docweb/login. Accordingly change all the functionality.

- [ ] Beautify the login page.

**Comment by mridubhatnagar** [comment]
Hey did you add any model named UserProfile?

I took a pull. And, I am trying to re-push my changes. But, it says no table repo.user_userprofile. 
Ran migrations and migrate. There it is showing no changes detected.

**Comment by mridubhatnagar** [comment]
I tried running `python manage.py makemigrations repo` that didn't help

**Comment by hseritt** [comment]
Yes. You should see it in models.py.

**Comment by hseritt** [comment]
For now, can you run reset-data.sh ?

**Comment by mridubhatnagar** [comment]
Ok

**Comment by mridubhatnagar** [comment]
Can you guide a bit with CSS?

All other changes are done. And things are working as expected.

**Comment by mridubhatnagar** [comment]
Below is /docweb/login/

updated_login

Below is /docweb/ - gets visible only when user is logged in.
docweb_main

When user logs out. Again user will get redirected to /docweb/login/

**Comment by mridubhatnagar** [comment]
- [ ] users app removed. Everything is in docweb.

- [ ] login page is /docweb/login/

- [ ] when user logs out. He/she gets redirected to /docweb/login/ and gets logged out from system.

**Comment by hseritt** [comment]
Yes, I will help with the CSS bit. Thanks very much for your work!

-Harlin

**Comment by hseritt** [comment]
Looks like this is what we're after. I will merge it :-)

**Pull request merged**
